# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [10]:
import numpy as np
# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

Warray = np.array(weight)
Harray = np.array(height)

bodymass = Warray / (Harray ** 2) * 730
print(bodymass)
# OUTPUT: [16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
# 22.06222222]




[16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
 22.06222222]


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [24]:
"""
Example Result
array([[14.21633515,  7.98846653,  9.64140715],
       [ 6.30982234,  9.96414331,  8.43153688],
       [14.73102068, 11.76072894, 14.23356121]])
"""
def makeMatrix(low,high,shape,data_type = float):
    result = np.random.uniform(low, high, shape)
    print(result)
makeMatrix(0,10, (3,3))


[[7.51908733 4.96369195 3.33371902]
 [7.68208021 5.54835252 3.7475201 ]
 [5.3926778  7.5594195  7.96823655]]


### #3 - Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [49]:
import csv
import numpy as np

#Test to make sure you have the correct data
def open_csv(filename, d = ','):
    data = []
    with open(filename, encoding = 'utf-8') as mData:
        info = csv.reader(mData, delimiter = d)
        for row in info:
            data.append(row)
    return data

hitting_2017 = open_csv('redsox_2017_hitting.txt')
hitting_2018 = open_csv('redsox_2018_hitting.txt')

print(hitting_2017[0:1])
print(hitting_2018[0:1])
ls = [type(item) for item in hitting_2017[0]]
print(ls)

[['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']]
[['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']]
[<class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>]


In [67]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

def load_data(filename, d = ','):
    data = np.genfromtxt(filename, delimiter = d, skip_header = 1,
                        usecols = np.arange(0,27), invalid_raise = False,
                        names = FIELDS, dtype = DATATYPES)
    return data

hits_2017 = load_data('redsox_2017_hitting.txt')

SLG2017 = hits_2017['SLG']
print(SLG2017)

hits_2018 = load_data('redsox_2018_hitting.txt')

SLG2018 = hits_2018['SLG']
print(SLG2018)

total_2017 = np.sum(SLG2017)
total_2018 = np.sum(SLG2018)

print (f'total SLG 2017: {total_2017}')
print (f'total SLG 2018: {total_2018}')
print(f' Total SLG in 2017 was higher than total SLG in 2018')

[0.404 0.443 0.392 0.403 0.482 0.424 0.402 0.459 0.429 0.354 0.387 0.333
 0.539 0.243 0.262 0.354 0.342 0.339 0.328 0.306 0.222 0.2   1.   ]
[0.279 0.433 0.388 0.522 0.433 0.465 0.403 0.64  0.629 0.411 0.283 0.328
 0.395 0.507 0.311 0.415 0.389 0.261 0.091 0.167]
total SLG 2017: 9.04699993133545
total SLG 2018: 7.75
 Total SLG in 2017 was higher than total SLG in 2018
